### PR TITLE
Zxp-provider can return a cmd/a path to ZXPSignCmd tool.

### PR DESCRIPTION
**Pull request by Lilipi**
- Cut and pass correctly command and arguments to spawn command
- Otherwise works like before

Links with https://github.com/fcamarlinghi/grunt-cep/issues/36 and https://github.com/codearoni/zxp-provider/pull/14

### CODE REVIEW

**Comment by fcamarlinghi** [comment]
Thanks for the PR, but I'm not a fan of the proposed changes.

The main concern is that the resulting code is far more complex and difficult to read than the original implementation. While I understand you need to split the command returned by _zxp-provider_ in order to pass the ZXPSignCmd  path to Wine, it's a very particular use case and as such it should be kept outside _grunt-cep_ or implemented in a different way. A possible solution might be to refactor the code to build the full command string manually and run it by setting `shell: true` in the options passed to `grunt.util.spawn`. However, it's a pretty big change which might break existing setups and I unfortunately don't have enough time in my hands right now to look into that.

The second concern is that you implemented the new functionality only for the "sign" command. I understand that's what you need in your particular use case, but it creates inconsistencies in the API when using the "certificate" command. A better place to implement support for the new `require('zxp-provider').env` option would be outside of the single commands, where the "zxp_path" [is first loaded](https://github.com/fcamarlinghi/grunt-cep/blob/a35dcb7592f2d3b2b8ee77262b0936c463f0a882/tasks/lib/zxp.js#L27).

I think your best bet in the immediate future is to use a custom version of _grunt-cep_ in your setup.

**Comment by Lilipi** [comment]
Thanks for your feedback ,
I've updated my PR on zxp-provider this morning and didn't have the time to go back to this one. I did this one really fast so clearly it isn't coded in the best way.

When my PR on zxp-provider will be accepted (if it happens) ; I will update this one too to load zxp path correctly at the first time. 

Your feedbacks are true, I didn't pay attention to the other commands and will correct that later too.


I'm using my "custom" grunt-cep version on my setup right now so it's not a problem, but it would be great if it could be included the right way in your module.

I will work on it if you agree.

**Comment by fcamarlinghi** [comment]
Sorry for the delay in getting back to you and thanks for updating the PR. I'll test and integrate the changes as soon as I find some time.

**Comment by Lilipi** [comment]
Hi,
Don't worry, no problem.
My PR on zxp-provider module is not accepted yet.
Thanks

**Comment by Lilipi** [comment]
Hi,
It seems like zxp-provider's owner doesn't want to update his module.
I will modify this PR to be indepedent of this upgrade (and only modify how command is executed)

Thanks

**Pull request closed without merging**
